apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    user: ${INFLUXDB_USER}
    url: http://influxdb:8086
    jsonData:
      dbName: ${INFLUXDB_DB}
      httpMode: GET
    secureJsonData:
      password: ${INFLUXDB_USER_PASSWORD}
